
/**
 This file is automatically generated by UIEditor. It defines the layout and data bindings of
 all UISpec owned by the associated UIModel. Include the UIEditor module with your development
 build in order to browse, open and edit all UISpec in your application at runtime.
 
 (Last generated 29 Apr 2019 3:47:44pm)
 */

#pragma once

/** This file is included early in the class defintion scope of WidgetsExample */
    
DEFINE_SYMBOL (Transcript);
DEFINE_SYMBOL (Progress);
DEFINE_SYMBOL (List);
DEFINE_SYMBOL (Settings);
DEFINE_SYMBOL (Colours);
DEFINE_SYMBOL (TabContents);
DEFINE_SYMBOL (TabSelection);
    
METACLASS_BEGIN (WidgetsExample, EmbeddedUIModel)

String getSpecsFilename() const override { return __FILE__; }
    
/** Use these aspects for change propagation in WidgetsExample */
Array<Aspect> getAspects() const override { return { Transcript, Progress, List, Settings, Colours, TabContents, TabSelection }; }

METACLASS_END
   
/** Use these globals to create pre-defined user interfaces for WidgetsExample */
static WeakReference<UISpec> DefaultSpec;


