/**
 This file was automatically generated by UIEditor ($TIME)
 */

#pragma once

$NS1

$SYMBOLS

class $MODEL  : public $PARENT
{
public:
    
#include "$INCLUDE"
    
    $MODEL (UIModel* parent);
   ~$MODEL ();
    
    // Implement your model here
    
private:
    
};

$NS2

