/**
 This file is automatically generated by UIEditor. It defines the layout and data bindings of
 all UISpec owned by the associated UIModel. Include the UIEditor module with your development
 build in order to browse, open and edit all UISpec in your application at runtime.
 
 (Last generated $TIME)
 */

#pragma once

/** This file is included early in the class defintion scope of $MODEL */
    
$SYMBOLS
    
METACLASS_BEGIN ($MODEL, $PARENT)
$NS
String getSpecsFilename() const override { return __FILE__; }
    
/** Use these aspects for change propagation in $MODEL */
Array<Aspect> getAspects() const override { return { $ASPECTS }; }

METACLASS_END
   
/** Use these globals to create pre-defined user interfaces for $MODEL */
$GLOBALS

