/**
 This file is automatically generated by UIEditor. It defines the layout and data bindings of
 all UISpec owned by the associated UIModel. Include the UIEditor module with your development
 build in order to browse, open and edit all UISpec in your application at runtime.
 
 (Last generated $TIME)
 */

#pragma once

$NS1

class $MODEL  : public $PARENT
{
public:
    
#include "$INCLUDE"
    
    $MODEL ();
   ~$MODEL ();
    
    const String getWindowTitle () override { return "Untitled"; }
    
private:
    
};

$NS2

