
/**
 This file is automatically generated by UIEditor. It defines the layout and data bindings of
 all UISpec owned by the associated UIModel. Include the UIEditor module with your development
 build in order to browse, open and edit all UISpec in your application at runtime.
 
 (Last generated 28 Apr 2019 8:48:22pm)
 */

#pragma once
    
/** This file is included early in the class defintion scope of MainModel */
    
DEFINE_SYMBOL (Transcript);
DEFINE_SYMBOL (Progress);
DEFINE_SYMBOL (List);
DEFINE_SYMBOL (Settings);
DEFINE_SYMBOL (TabContents);
DEFINE_SYMBOL (TabSelection);
    
METACLASS_BEGIN (MainModel, WindowUIModel)
    
String getSpecsFilename() const override { return __FILE__; }
    
/** Use these aspects for change propagation in MainModel */
Array<Aspect> getAspects() const override { return { Transcript, Progress, List, Settings, TabContents, TabSelection }; }

METACLASS_END
   
/** Use these globals to create pre-defined user interfaces for MainModel */
static WeakReference<UISpec> MainWindowSpec;


